import HeroSection from '@/components/HeroSection'
import OurServices from '@/components/OurServices'
import AboutUs from '@/components/AboutUs'
import Testimonial from '@/components/Testimonial'
import Quote from '@/components/Quote'
import Footer from '@/components/Footer'
import WhyGoForSolar from '@/components/WhyGoForSolar'
import BackToTop from '@/components/BackToTop'
import Head from 'next/head'


export default function Home() {
  return (
    <>
    <Head>
        <title>Solar Solutions-by Choudhary Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/solar_logo.png" />
      </Head>
    <main className='max-w-[1440px] mx-auto font-source_sans_pro relative'>
    <HeroSection/>
    <WhyGoForSolar/>
    <AboutUs/>
    <OurServices/>
    <Testimonial/>
    <Quote/>
    <Footer/>
    <BackToTop/>
    </main>
    </>

  )
}
